site_name: Magicka Wiki
site_url: https://d95a-4c1d.github.io/Magicka-wiki/
repo_url: https://github.com/d95a-4c1d/Magicka-wiki
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - content.action.edit
nav:
  - 简介: index.md
  - 剧情: 剧情.md
  - 魔法:
    - 魔法: 魔法/魔法简介.md
    - 法阵:
      - 法阵简介: 法阵/法阵简介.md
      - 复制法阵: 法阵/复制法阵.md
      - 复活法阵: 法阵/复活法阵.md
    - 烹饪: 魔法/烹饪.md
    - 炼金: 魔法/炼金.md
    - 符咒: 魔法/符咒.md
    - 祷文: 魔法/祷文.md
    - 亡者再生: 魔法/亡者再生.md
  - 物品:
    - 粉末: 粉末.md
    - 物品特性: 物品特性.md
    - 材料特性: 材料特性.md
  - 机制:
    - 总体机制: 机制/机制.md
  - 敌人:
    - 类型: 类型.md
    - 机制: 敌人机制.md
    - 寻路: 寻路.md
  - 载具:
    - 载具生成: 载具生成.md
    - 载具机制: 载具机制.md
  - 玩家:
    - 运动: 运动.md
    - 背包: 背包.md
    - 操作: 操作.md
  - 画面:
    - 画面设定: 画面/画面设定.md
    - 艺术设定集: 画面/艺术设定集.md
  - 地图:
    - 地图搭建: 地图搭建.md
    - 地图生成: 地图生成.md
  - 项目开发:
    - 未来安排: 项目开发/未来安排.md
    - 结构: 项目开发/开发结构.md
    - 注意事项: 项目开发/注意事项.md
    